// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDDzGU8iN6hLe9ZNF_kVW41X7eXWcy84',
    appId: '1:324697010498:web:26865d2ace7e869aa398db',
    messagingSenderId: '324697010498',
    projectId: 'roseo-study',
    authDomain: 'roseo-study.firebaseapp.com',
    storageBucket: 'roseo-study.firebasestorage.app',
    measurementId: 'G-TDZX8N9ZGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCicXk-TRs_9ZO7mIQOTaY_C1juV59j4Uc',
    appId: '1:324697010498:android:b7851ba90f05cbf7a398db',
    messagingSenderId: '324697010498',
    projectId: 'roseo-study',
    storageBucket: 'roseo-study.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_XD-dOX6ksO7hGklDXJIMB0vCCIi3D0',
    appId: '1:324697010498:ios:a36e2dc6c8e1aaf8a398db',
    messagingSenderId: '324697010498',
    projectId: 'roseo-study',
    storageBucket: 'roseo-study.firebasestorage.app',
    iosBundleId: 'com.example.roseoStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_XD-dOX6ksO7hGklDXJIMB0vCCIi3D0',
    appId: '1:324697010498:ios:a36e2dc6c8e1aaf8a398db',
    messagingSenderId: '324697010498',
    projectId: 'roseo-study',
    storageBucket: 'roseo-study.firebasestorage.app',
    iosBundleId: 'com.example.roseoStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARDDzGU8iN6hLe9ZNF_kVW41X7eXWcy84',
    appId: '1:324697010498:web:e06b5abb4f1ea065a398db',
    messagingSenderId: '324697010498',
    projectId: 'roseo-study',
    authDomain: 'roseo-study.firebaseapp.com',
    storageBucket: 'roseo-study.firebasestorage.app',
    measurementId: 'G-8BWSMR2KSR',
  );
}
